# Generated by Django 4.2.2 on 2023-07-03 03:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('event_description', models.TextField(max_length=500)),
                ('number_of_guests', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(choices=[('*', ''), ('N', 'New York'), ('M', 'Miami'), ('L', 'Los Angeles'), ('W', 'Washington, D.C.'), ('V', 'Las Vegas')], default='*', max_length=1)),
            ],
        ),
    ]
